# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/motor.xdc

# Block Designs: bd/motor/motor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motor || ORIG_REF_NAME==motor}]

# IP: bd/motor/ip/motor_processing_system7_0_0/motor_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motor_processing_system7_0_0 || ORIG_REF_NAME==motor_processing_system7_0_0}]

# IP: bd/motor/ip/motor_processing_system7_0_axi_periph_0/motor_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motor_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==motor_processing_system7_0_axi_periph_0}]

# IP: bd/motor/ip/motor_rst_processing_system7_0_100M_0/motor_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motor_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==motor_rst_processing_system7_0_100M_0}]

# IP: bd/motor/ip/motor_motor_0_0/motor_motor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motor_motor_0_0 || ORIG_REF_NAME==motor_motor_0_0}]

# IP: bd/motor/ip/motor_auto_pc_0/motor_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==motor_auto_pc_0 || ORIG_REF_NAME==motor_auto_pc_0}]

# XDC: bd/motor/ip/motor_processing_system7_0_0/motor_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==motor_processing_system7_0_0 || ORIG_REF_NAME==motor_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/motor/ip/motor_rst_processing_system7_0_100M_0/motor_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==motor_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==motor_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/motor/ip/motor_rst_processing_system7_0_100M_0/motor_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==motor_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==motor_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/motor/ip/motor_rst_processing_system7_0_100M_0/motor_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/motor/ip/motor_auto_pc_0/motor_auto_pc_0_ooc.xdc

# XDC: bd/motor/motor_ooc.xdc
